{{- if .Values.loginService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.loginService.name }}-secret
  namespace: {{ include "microforge.namespace" . }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.loginService.secrets.dbUsername }}
  DB_PASSWORD: {{ .Values.loginService.secrets.dbPassword }}
  JWT_SECRET: {{ .Values.loginService.secrets.jwtSecret }}
{{- end }}

