{{- if .Values.metadataService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.metadataService.name }}-secret
  namespace: {{ include "microforge.namespace" . }}
type: Opaque
stringData:
  FLASK_SECRET_KEY: {{ .Values.metadataService.secrets.flaskSecretKey }}
{{- end }}

