{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "microforge.namespace" . }}
  labels:
    {{- range $key, $value := .Values.namespace.labels }}
    {{ $key }}: {{ $value }}
    {{- end }}
{{- end }}

