{{- if .Values.notificationMysql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.notificationMysql.name }}-secret
  namespace: {{ include "microforge.namespace" . }}
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ .Values.notificationMysql.secrets.rootPassword }}
{{- end }}

