{{- if .Values.notificationMysql.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.notificationMysql.name }}-config
  namespace: {{ include "microforge.namespace" . }}
data:
  MYSQL_DATABASE: {{ .Values.notificationMysql.config.database }}
{{- end }}

