{{- if .Values.notificationService.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.notificationService.name }}-secret
  namespace: {{ include "microforge.namespace" . }}
type: Opaque
stringData:
  MYSQL_USER: {{ .Values.notificationService.secrets.mysqlUser }}
  MYSQL_PASSWORD: {{ .Values.notificationService.secrets.mysqlPassword }}
{{- end }}

