apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
  namespace: microforge-dev-ns
  labels:
    app: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-service
  template:
    metadata:
      labels:
        app: frontend-service
    spec:
      containers:
        - name: frontend-service
          image: manojmdocker14/microforge-frontend-service:v1.1.5
          ports:
            - containerPort: 80
          env:
            - name: REACT_APP_LOGIN_SERVICE_URL
              value: http://api.microforge.manojm.site
            - name: REACT_APP_AUTH_SERVICE_URL
              value: http://api.microforge.manojm.site
            - name: REACT_APP_METADATA_SERVICE_URL
              value: http://api.microforge.manojm.site
            - name: REACT_APP_NOTIFICATION_SERVICE_URL
              value: http://api.microforge.manojm.site