apiVersion: v1
kind: Service
metadata:
  name: login-mysql
  namespace: microforge-dev-ns
  labels:
    app: login-mysql
spec:
  selector:
    app: login-mysql
  type: ClusterIP
  ports:
    - name: login-mysql-port
      port: 3306