apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: microforge-dev-ns
spec:
  selector:
    app:  login-service
  type: ClusterIP
  ports:
  - name:  login-service-port
    port:  8081
    targetPort:  8081