apiVersion: v1
kind: ConfigMap
metadata:
  name: login-service-config
  namespace: microforge-dev-ns
data:
  LOGIN_SERVICE_PORT: "8081"
  DB_PORT: "3306"
  DB_NAME: empdir
  JWT_EXPIRATION_MS: "86400000"
  NOTIFICATION_SERVICE_URL: http://api.microforge.manojm.site
---
apiVersion: v1
kind: Service
metadata:
  name: login-service
  namespace: microforge-dev-ns
  labels:
    app: login-service
spec:
  selector:
    app:  login-service
  type: ClusterIP
  ports:
  - name:  login-service-port
    port:  8081
    targetPort:  8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-service
  namespace: microforge-dev-ns
  labels:
    app: login-service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        
      maxUnavailable: 0
  selector:
    matchLabels:
      app: login-service
  template:
    metadata:
      labels:
        app: login-service
    spec:
      containers:
        - name: login-service
          image: manojmdocker14/microforge-login-service:v1.2.0
          ports:
            - containerPort: 8081
          livenessProbe:
            httpGet:
              path: /actuator/health 
              port: 8081
            initialDelaySeconds: 70
            periodSeconds: 20
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health 
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          env:
            - name: DB_HOST
              value: login-mysql
          envFrom:
            - configMapRef:
                name:  login-service-config
            - secretRef:
                name:  login-service-secret
