apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microforge-ingress
  namespace: microforge-dev-ns
  labels:
    app.kubernetes.io/name: microforge-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: microforge.manojm.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend-service
            port: 
              number: 80
  - host: api.microforge.manojm.site
    http:
      paths:
      - path: /api/auth/login(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: login-service
            port:
              number: 8081
      - path: /api/auth/register(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: login-service
            port:
              number: 8081
      - path: /api/users(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: login-service
            port:
              number: 8081
      


