apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microforge-ingress
  namespace: microforge-dev-ns
  labels:
    app.kubernetes.io/name: microforge-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"

    # CORS Configuration
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-origin: "*"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Authorization, Content-Type, Accept, Origin, User-Agent, Cache-Control, Keep-Alive"
    nginx.ingress.kubernetes.io/cors-max-age: "86400"

    # nginx.ingress.kubernetes.io/configuration-snippet: |
    #   add_header Origin-Agent-Cluster "?0" always;
spec:
  ingressClassName: nginx
  rules:
  - host: microforge.manojm.site
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: frontend-service
            port: 
              number: 80
  - host: api.microforge.manojm.site
    http:
      paths:
      - path: /api/auth/login(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: login-service
            port:
              number: 8081

      - path: /api/auth/register(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: login-service
            port:
              number: 8081

      - path: /api/users(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: login-service
            port:
              number: 8081

      - path : /api/metadata(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name:  metadata-service
            port:
              number: 8084
      
      - path : /api/stress(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name:  metadata-service
            port:
              number: 8084

      - path : /api/notification(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name:  notification-service
            port: 
              number: 8083

      - path: /api/validate(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name:  auth-service
            port: 
              number: 8082


