apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-mysql-config
  namespace: microforge-dev-ns
data:
  MYSQL_DATABASE: empdirempnotification
---
apiVersion: v1
kind: Service
metadata:
  name: notification-mysql
  namespace: microforge-dev-ns
  labels:
    app: notification-mysql
spec:
  selector:
    app: notification-mysql
  type: ClusterIP
  ports:
    - name: notification-mysql-port
      port: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-mysql
  namespace: microforge-dev-ns
  labels:
    app: notification-mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-mysql
  template:
    metadata:
      labels:
        app: notification-mysql
    spec:
      containers:
        - name: notification-mysql
          image: manojmdocker14/microforge-notifications-mysql:v1.0.0
          ports:
            - containerPort: 3306
          envFrom:
            - configMapRef:
                name: notification-mysql-config
            - secretRef:
                name: notification-mysql-secret
