apiVersion: v1
kind: Service
metadata:
  name: notification-mysql
  namespace: microforge-dev-ns
  labels:
    app: notification-mysql
spec:
  selector:
    app: notification-mysql
  type: ClusterIP
  ports:
    - name: notification-mysql-port
      port: 3306