apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: microforge-dev-ns
data:
  MYSQL_DATABASE: empnotification
  MYSQL_PORT: "3306"
  NOTIFICATION_SERVICE_PORT: "8083"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microforge-dev-ns
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  type: ClusterIP
  ports:
    - name: notification-service-port
      port: 8083
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: microforge-dev-ns
  labels:
    app: notification-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: manojmdocker14/microforge-notification-service:v1.1.0
          ports:
            - containerPort: 8083
          env:
            - name: MYSQL_HOST
              value: notification-mysql
          envFrom:
            - configMapRef:
                name: notification-service-config
            - secretRef:
                name: notification-service-secret
