apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: microforge-dev-ns
  labels:
    app: notification-service
spec:
  selector:
    app: notification-service
  type: ClusterIP
  ports:
    - name: notification-service-port
      port: 8083