apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: microforge-dev-ns
data:
  MYSQL_DATABASE: empnotification
  MYSQL_PORT: "3306"
  NOTIFICATION_SERVICE_PORT: "8083"