
services:
  metadata-service:
    image: manojmdocker14/microforge-metadata-service:v1.0.0
    container_name: metadata-service
    ports:
      - "8084:8084"
    environment:
      - FLASK_SECRET_KEY=f9731e7a0774ddebd70643e8c6046f4dc0ddf3eec637be8cb641f0e9d5e8dfd0
      - FLASK_ENV=development
      - METADATA_SERVICE_PORT=${METADATA_SERVICE_PORT}
    restart: unless-stopped
    networks:
      - microforge-network

  auth-service:
    image: manojmdocker14/microforge-auth-service:v1.0.0
    container_name: auth-service
    ports:
      - "8082:8082"
    environment:
      - AUTH_SERVICE_PORT=${AUTH_SERVICE_PORT}
    networks:
      - microforge-network

  frontend-service:
    image: manojmdocker14/microforge-frontend-service:v1.1.0
    container_name: frontend-service
    ports:
      - "3000:80"
    depends_on:
      - metadata-service
      - auth-service
      - login-service
      - notification-service
    env_file:
      - .env
    networks:
      - microforge-network

  login-mysql:
    image: manojmdocker14/microforge-users-mysql:v1.0.0
    container_name: login-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${LOGIN_SERVICE_DB_PASSWORD}
      MYSQL_DATABASE: ${LOGIN_SERVICE_DB_NAME}
    volumes:
      - mysql-data-login:/var/lib/mysql
    ports:
      - "3308:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -D $$MYSQL_DATABASE -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microforge-network

  login-service:
    image: manojmdocker14/microforge-login-service:v1.1.0
    container_name: login-service
    ports:
      - 8081:8081
    environment:
      - LOGIN_SERVICE_PORT=${LOGIN_SERVICE_PORT}
      - DB_HOST=login-mysql
      - DB_PORT=${LOGIN_SERVICE_DB_PORT}
      - DB_NAME=${LOGIN_SERVICE_DB_NAME}
      - DB_USERNAME=${LOGIN_SERVICE_DB_USERNAME}
      - DB_PASSWORD=${LOGIN_SERVICE_DB_PASSWORD}
      - JWT_SECRET=${LOGIN_SERVICE_JWT_SECRET}
      - JWT_EXPIRATION_MS=${LOGIN_SERVICE_JWT_EXPIRATION_MS}
      - NOTIFICATION_SERVICE_URL=http://notification-service:${NOTIFICATION_SERVICE_PORT}
    depends_on:
      login-mysql:
        condition: service_healthy
    networks:
      - microforge-network

  notification-mysql:
    image: manojmdocker14/microforge-notifications-mysql:v1.0.0
    container_name: notification-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${NOTIFICATION_SERVICE_DB_PASSWORD}
      - MYSQL_DATABASE=${NOTIFICATION_SERVICE_DB_DATABASE}
    volumes:
      - mysql-data-notification:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD-SHELL", "mysql -h localhost -u root -p$$MYSQL_ROOT_PASSWORD -D $$MYSQL_DATABASE -e 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - microforge-network

  notification-service:
    image: manojmdocker14/microforge-notification-service:v1.0.0
    container_name: notification-service
    ports:
      - "8083:8083"
    environment:
      - MYSQL_HOST=notification-mysql
      - MYSQL_USER=${NOTIFICATION_SERVICE_DB_USER}
      - MYSQL_PASSWORD=${NOTIFICATION_SERVICE_DB_PASSWORD}
      - MYSQL_DATABASE=${NOTIFICATION_SERVICE_DB_DATABASE}
      - MYSQL_PORT=${NOTIFICATION_SERVICE_DB_PORT}
      - NOTIFICATION_SERVICE_PORT=${NOTIFICATION_SERVICE_PORT}
    depends_on:
      notification-mysql:
        condition: service_healthy
    networks:
      - microforge-network

networks:
  microforge-network:
    driver: bridge

volumes:
  mysql-data-login:
  mysql-data-notification: