name: Docker Build & Push Services

on:
  push:
    branches: [ "master" , "docker/setup-push-pipeline"]
  # Manual Trigger with dropdown
  workflow_dispatch:
    inputs:
      service_target:
        description: 'Which service to build?'
        required: true
        type: choice
        default: 'all'
        options: 
          - all
          - auth-service
          - frontend-service
          - login-service
          - metadata-service
          - notification-service
      version:
        description: 'Version Tag (e.g., v1.2.0)'
        required: false
        default: ''

jobs:
  build-and-push-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: auth-service
            image_suffix: microforge-auth-service
            version: v1.0.0
          - name: frontend-service
            image_suffix: microforge-frontend-service
            version: v1.1.0
          - name: login-service
            image_suffix: microforge-login-service
            version: v1.1.0
          - name: metadata-service
            image_suffix: microforge-metadata-service
            version: v1.0.0
          - name: notification-service
            image_suffix: microforge-notification-service
            version: v1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Version
        id: versioning
        run: |
          if [[ "${{ inputs.version }}" != "" ]]; then
            echo "VERSION=${{ inputs.version }}" >> $GITHUB_ENV
          else
            echo "VERSION=${{ matrix.service.version }}" >> $GITHUB_ENV
          fi
      - name: Build and push
        uses: docker/build-push-action@v5
        # LOGIC: Run if target is 'all' OR if the current matrix service matches the input
        if: ${{ inputs.service_target == 'all' || inputs.service_target == matrix.service.name || github.event_name == 'push' }}
        with:
          context: .
          file: ./Dockerfile
          target: ${{ matrix.service.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/microforge:${{ matrix.service.name }}-${{ env.VERSION }}
            ${{ secrets.DOCKER_USERNAME }}/microforge:${{ matrix.service.name }}-latest
            ${{ secrets.DOCKER_USERNAME }}/microforge:${{ matrix.service.name }}-${{ github.sha }}
            ${{ inputs.version != '' && format('{0}/microforge:{1}-{2}', secrets.DOCKER_USERNAME, matrix.service.name, inputs.version) || '' }}
