name: Docker Build & Push Services

on:
  push:
    branches: [ "master",'docker/setup-push-pipeline']
  # Manual Trigger with dropdown
  workflow_dispatch:
    inputs:
      service_target:
        description: 'Which service to build?'
        required: true
        type: choice
        default: 'all'
        options: 
          - all
          - auth-service
          - frontend-service
          - login-service
          - metadata-service
          - notification-service
      version:
        description: 'Version Tag (e.g., v1.2.0)'
        required: false
        default: ''

jobs:
  build-and-push-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: auth-service
            image_suffix: microforge-auth-service
          - name: frontend-service
            image_suffix: microforge-frontend-service
          - name: login-service
            image_suffix: microforge-login-service
          - name: metadata-service
            image_suffix: microforge-metadata-service
          - name: notification-service
            image_suffix: microforge-notification-service

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        # LOGIC: Run if target is 'all' OR matches the current service name
        if: ${{ inputs.service_target == 'all' || inputs.service_target == matrix.service || github.event_name == 'push' }}
        env:
          # Logic: Only create this tag if input.version is NOT empty
          MANUAL_TAG: ${{ inputs.version != '' && format('{0}/microforge:{1}-{2}', secrets.DOCKER_USERNAME, matrix.service, inputs.version) || '' }}
        with:
          context: .
          file: ./Dockerfile
          target: ${{ matrix.service.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/microforge:${{ matrix.service.name }}-latest
            ${{ secrets.DOCKER_USERNAME }}/microforge:${{ matrix.service.name }}-${{ github.sha }}
            ${{ env.MANUAL_TAG }}
