name: Docker Build & Push Services

on:
  push:
    branches: [ "master"]

jobs:
  build-and-push-services:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - name: auth-service
            image_suffix: microforge-auth-service
            version: v1.0.0
          - name: frontend-service
            image_suffix: microforge-frontend-service
            version: v1.1.0
          - name: login-service
            image_suffix: microforge-login-service
            version: v1.1.0
          - name: metadata-service
            image_suffix: microforge-metadata-service
            version: v1.0.0
          - name: notification-service
            image_suffix: microforge-notification-service
            version: v1.0.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          target: ${{ matrix.service.name }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.image_suffix }}:${{ matrix.service.version }}
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.image_suffix }}:latest
            ${{ secrets.DOCKER_USERNAME }}/${{ matrix.service.image_suffix }}:${{github.sha}}
