name: Infrastructure Deployment
on:
    push:
      branches:
        - stage
        - master
        - feature/workflows
      paths:
        - ./infrastructure/*
        - ./.github/workflows/*
    workflow_dispatch:

env:
  ENVIRONMENT: ${{github.ref == 'refs/heads/master' && 'producation' || 'stage'}}

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./infrastructure

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4

      - name: AWS configure
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{secrets.AWS_REGION}}
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Setup terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform init
        id: init
        run: terraform init -backend-config="bucket=${{secrets.TF_STATE_BUCKET}}"

      - name: Terraform format
        id: fmt
        run: terraform fmt -check

      - name: Terraform validate
        id: validate
        run: terraform validate

      - name: Terraform workspace
        run: terraform workspace select ${{env.ENVIRONMENT}} || terraform workspace new ${{env.ENVIRONMENT}}

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color -input=false -out planfile
        continue-on-error: true

      - name: Terraform plan status
        if: steps.plan.outcome == 'failure'
        run: exit 1

      - name: Terraform apply
        run: terraform apply -auto-approve -no-color -input=false -parallelism=1 planfile

      - name: Kubernetes git nodes
        run: kubectl get nodes
